// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty/internal/domain/balance/usecase (interfaces: BalanceUsecase)
//
// Generated by this command:
//
//	mockgen -destination=balance_usecase.go -package=mocks loyalty/internal/domain/balance/usecase BalanceUsecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty/internal/domain/balance/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBalanceUsecase is a mock of BalanceUsecase interface.
type MockBalanceUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceUsecaseMockRecorder
	isgomock struct{}
}

// MockBalanceUsecaseMockRecorder is the mock recorder for MockBalanceUsecase.
type MockBalanceUsecaseMockRecorder struct {
	mock *MockBalanceUsecase
}

// NewMockBalanceUsecase creates a new mock instance.
func NewMockBalanceUsecase(ctrl *gomock.Controller) *MockBalanceUsecase {
	mock := &MockBalanceUsecase{ctrl: ctrl}
	mock.recorder = &MockBalanceUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceUsecase) EXPECT() *MockBalanceUsecaseMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockBalanceUsecase) GetBalance(ctx context.Context, userID int64) (model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockBalanceUsecaseMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockBalanceUsecase)(nil).GetBalance), ctx, userID)
}
