// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty/internal/domain/order/service (interfaces: OrdersService,OrderNumberValidator)
//
// Generated by this command:
//
//	mockgen -destination=order_service.go -package=mocks loyalty/internal/domain/order/service OrdersService,OrderNumberValidator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty/internal/domain/accrual/model"
	model0 "loyalty/internal/domain/order/model"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockOrdersService is a mock of OrdersService interface.
type MockOrdersService struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersServiceMockRecorder
	isgomock struct{}
}

// MockOrdersServiceMockRecorder is the mock recorder for MockOrdersService.
type MockOrdersServiceMockRecorder struct {
	mock *MockOrdersService
}

// NewMockOrdersService creates a new mock instance.
func NewMockOrdersService(ctrl *gomock.Controller) *MockOrdersService {
	mock := &MockOrdersService{ctrl: ctrl}
	mock.recorder = &MockOrdersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersService) EXPECT() *MockOrdersServiceMockRecorder {
	return m.recorder
}

// LoadOrders mocks base method.
func (m *MockOrdersService) LoadOrders(ctx context.Context, userID int64) ([]model0.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadOrders", ctx, userID)
	ret0, _ := ret[0].([]model0.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadOrders indicates an expected call of LoadOrders.
func (mr *MockOrdersServiceMockRecorder) LoadOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadOrders", reflect.TypeOf((*MockOrdersService)(nil).LoadOrders), ctx, userID)
}

// UpdateFromAccrual mocks base method.
func (m *MockOrdersService) UpdateFromAccrual(ctx context.Context, orderNumber string, accrualStatus model.AccrualStatus, accrual *decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFromAccrual", ctx, orderNumber, accrualStatus, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFromAccrual indicates an expected call of UpdateFromAccrual.
func (mr *MockOrdersServiceMockRecorder) UpdateFromAccrual(ctx, orderNumber, accrualStatus, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFromAccrual", reflect.TypeOf((*MockOrdersService)(nil).UpdateFromAccrual), ctx, orderNumber, accrualStatus, accrual)
}

// UploadOrder mocks base method.
func (m *MockOrdersService) UploadOrder(ctx context.Context, userID int64, number string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadOrder", ctx, userID, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadOrder indicates an expected call of UploadOrder.
func (mr *MockOrdersServiceMockRecorder) UploadOrder(ctx, userID, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadOrder", reflect.TypeOf((*MockOrdersService)(nil).UploadOrder), ctx, userID, number)
}

// MockOrderNumberValidator is a mock of OrderNumberValidator interface.
type MockOrderNumberValidator struct {
	ctrl     *gomock.Controller
	recorder *MockOrderNumberValidatorMockRecorder
	isgomock struct{}
}

// MockOrderNumberValidatorMockRecorder is the mock recorder for MockOrderNumberValidator.
type MockOrderNumberValidatorMockRecorder struct {
	mock *MockOrderNumberValidator
}

// NewMockOrderNumberValidator creates a new mock instance.
func NewMockOrderNumberValidator(ctrl *gomock.Controller) *MockOrderNumberValidator {
	mock := &MockOrderNumberValidator{ctrl: ctrl}
	mock.recorder = &MockOrderNumberValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderNumberValidator) EXPECT() *MockOrderNumberValidatorMockRecorder {
	return m.recorder
}

// ValidateNumber mocks base method.
func (m *MockOrderNumberValidator) ValidateNumber(number string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateNumber", number)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateNumber indicates an expected call of ValidateNumber.
func (mr *MockOrderNumberValidatorMockRecorder) ValidateNumber(number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateNumber", reflect.TypeOf((*MockOrderNumberValidator)(nil).ValidateNumber), number)
}
