// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty/internal/domain/order/repository (interfaces: OrdersRepository)
//
// Generated by this command:
//
//	mockgen -destination=order_repository.go -package=mocks loyalty/internal/domain/order/repository OrdersRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty/internal/domain/order/model"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockOrdersRepository is a mock of OrdersRepository interface.
type MockOrdersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersRepositoryMockRecorder
	isgomock struct{}
}

// MockOrdersRepositoryMockRecorder is the mock recorder for MockOrdersRepository.
type MockOrdersRepositoryMockRecorder struct {
	mock *MockOrdersRepository
}

// NewMockOrdersRepository creates a new mock instance.
func NewMockOrdersRepository(ctrl *gomock.Controller) *MockOrdersRepository {
	mock := &MockOrdersRepository{ctrl: ctrl}
	mock.recorder = &MockOrdersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersRepository) EXPECT() *MockOrdersRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrdersRepository) Create(ctx context.Context, userID int64, number string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrdersRepositoryMockRecorder) Create(ctx, userID, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrdersRepository)(nil).Create), ctx, userID, number)
}

// ListByUser mocks base method.
func (m *MockOrdersRepository) ListByUser(ctx context.Context, userID int64) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockOrdersRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockOrdersRepository)(nil).ListByUser), ctx, userID)
}

// ListPending mocks base method.
func (m *MockOrdersRepository) ListPending(ctx context.Context) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockOrdersRepositoryMockRecorder) ListPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockOrdersRepository)(nil).ListPending), ctx)
}

// UpdateFromAccrual mocks base method.
func (m *MockOrdersRepository) UpdateFromAccrual(ctx context.Context, number string, status model.Status, accrual *decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFromAccrual", ctx, number, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFromAccrual indicates an expected call of UpdateFromAccrual.
func (mr *MockOrdersRepositoryMockRecorder) UpdateFromAccrual(ctx, number, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFromAccrual", reflect.TypeOf((*MockOrdersRepository)(nil).UpdateFromAccrual), ctx, number, status, accrual)
}
