// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty/internal/domain/order/usecase (interfaces: OrdersUsecase)
//
// Generated by this command:
//
//	mockgen -destination=order_usecase.go -package=mocks loyalty/internal/domain/order/usecase OrdersUsecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty/internal/domain/order/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrdersUsecase is a mock of OrdersUsecase interface.
type MockOrdersUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersUsecaseMockRecorder
	isgomock struct{}
}

// MockOrdersUsecaseMockRecorder is the mock recorder for MockOrdersUsecase.
type MockOrdersUsecaseMockRecorder struct {
	mock *MockOrdersUsecase
}

// NewMockOrdersUsecase creates a new mock instance.
func NewMockOrdersUsecase(ctrl *gomock.Controller) *MockOrdersUsecase {
	mock := &MockOrdersUsecase{ctrl: ctrl}
	mock.recorder = &MockOrdersUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersUsecase) EXPECT() *MockOrdersUsecaseMockRecorder {
	return m.recorder
}

// LoadOrders mocks base method.
func (m *MockOrdersUsecase) LoadOrders(ctx context.Context, userID int64) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadOrders", ctx, userID)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadOrders indicates an expected call of LoadOrders.
func (mr *MockOrdersUsecaseMockRecorder) LoadOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadOrders", reflect.TypeOf((*MockOrdersUsecase)(nil).LoadOrders), ctx, userID)
}

// UploadOrder mocks base method.
func (m *MockOrdersUsecase) UploadOrder(ctx context.Context, userID int64, number string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadOrder", ctx, userID, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadOrder indicates an expected call of UploadOrder.
func (mr *MockOrdersUsecaseMockRecorder) UploadOrder(ctx, userID, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadOrder", reflect.TypeOf((*MockOrdersUsecase)(nil).UploadOrder), ctx, userID, number)
}
