// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty/internal/domain/withdrawal/usecase (interfaces: WithdrawalsUsecase)
//
// Generated by this command:
//
//	mockgen -destination=withdrawal_usecase.go -package=mocks loyalty/internal/domain/withdrawal/usecase WithdrawalsUsecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty/internal/domain/withdrawal/model"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawalsUsecase is a mock of WithdrawalsUsecase interface.
type MockWithdrawalsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalsUsecaseMockRecorder
	isgomock struct{}
}

// MockWithdrawalsUsecaseMockRecorder is the mock recorder for MockWithdrawalsUsecase.
type MockWithdrawalsUsecaseMockRecorder struct {
	mock *MockWithdrawalsUsecase
}

// NewMockWithdrawalsUsecase creates a new mock instance.
func NewMockWithdrawalsUsecase(ctrl *gomock.Controller) *MockWithdrawalsUsecase {
	mock := &MockWithdrawalsUsecase{ctrl: ctrl}
	mock.recorder = &MockWithdrawalsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalsUsecase) EXPECT() *MockWithdrawalsUsecaseMockRecorder {
	return m.recorder
}

// ListWithdrawals mocks base method.
func (m *MockWithdrawalsUsecase) ListWithdrawals(ctx context.Context, userID int64) ([]model.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]model.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithdrawals indicates an expected call of ListWithdrawals.
func (mr *MockWithdrawalsUsecaseMockRecorder) ListWithdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithdrawals", reflect.TypeOf((*MockWithdrawalsUsecase)(nil).ListWithdrawals), ctx, userID)
}

// Withdraw mocks base method.
func (m *MockWithdrawalsUsecase) Withdraw(ctx context.Context, userID int64, orderNumber string, sum decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, orderNumber, sum)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockWithdrawalsUsecaseMockRecorder) Withdraw(ctx, userID, orderNumber, sum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockWithdrawalsUsecase)(nil).Withdraw), ctx, userID, orderNumber, sum)
}
