// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty/internal/domain/withdrawal/repository (interfaces: AccountRepository,WithdrawalsRepository)
//
// Generated by this command:
//
//	mockgen -destination=withdrawal_repository.go -package=mocks loyalty/internal/domain/withdrawal/repository AccountRepository,WithdrawalsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty/internal/domain/withdrawal/model"
	reflect "reflect"
	time "time"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// Withdraw mocks base method.
func (m *MockAccountRepository) Withdraw(ctx context.Context, userID int64, orderNumber string, sum decimal.Decimal, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, orderNumber, sum, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockAccountRepositoryMockRecorder) Withdraw(ctx, userID, orderNumber, sum, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockAccountRepository)(nil).Withdraw), ctx, userID, orderNumber, sum, now)
}

// MockWithdrawalsRepository is a mock of WithdrawalsRepository interface.
type MockWithdrawalsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalsRepositoryMockRecorder
	isgomock struct{}
}

// MockWithdrawalsRepositoryMockRecorder is the mock recorder for MockWithdrawalsRepository.
type MockWithdrawalsRepositoryMockRecorder struct {
	mock *MockWithdrawalsRepository
}

// NewMockWithdrawalsRepository creates a new mock instance.
func NewMockWithdrawalsRepository(ctrl *gomock.Controller) *MockWithdrawalsRepository {
	mock := &MockWithdrawalsRepository{ctrl: ctrl}
	mock.recorder = &MockWithdrawalsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalsRepository) EXPECT() *MockWithdrawalsRepositoryMockRecorder {
	return m.recorder
}

// ListByUser mocks base method.
func (m *MockWithdrawalsRepository) ListByUser(ctx context.Context, userID int64) ([]model.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockWithdrawalsRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockWithdrawalsRepository)(nil).ListByUser), ctx, userID)
}
