// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty/internal/domain/withdrawal/service (interfaces: WithdrawalsService)
//
// Generated by this command:
//
//	mockgen -destination=withdrawal_service.go -package=mocks loyalty/internal/domain/withdrawal/service WithdrawalsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "loyalty/internal/domain/withdrawal/model"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawalsService is a mock of WithdrawalsService interface.
type MockWithdrawalsService struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalsServiceMockRecorder
	isgomock struct{}
}

// MockWithdrawalsServiceMockRecorder is the mock recorder for MockWithdrawalsService.
type MockWithdrawalsServiceMockRecorder struct {
	mock *MockWithdrawalsService
}

// NewMockWithdrawalsService creates a new mock instance.
func NewMockWithdrawalsService(ctrl *gomock.Controller) *MockWithdrawalsService {
	mock := &MockWithdrawalsService{ctrl: ctrl}
	mock.recorder = &MockWithdrawalsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalsService) EXPECT() *MockWithdrawalsServiceMockRecorder {
	return m.recorder
}

// ListWithdrawals mocks base method.
func (m *MockWithdrawalsService) ListWithdrawals(ctx context.Context, userID int64) ([]model.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]model.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithdrawals indicates an expected call of ListWithdrawals.
func (mr *MockWithdrawalsServiceMockRecorder) ListWithdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithdrawals", reflect.TypeOf((*MockWithdrawalsService)(nil).ListWithdrawals), ctx, userID)
}

// Withdraw mocks base method.
func (m *MockWithdrawalsService) Withdraw(ctx context.Context, userID int64, orderNumber string, sum decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, orderNumber, sum)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockWithdrawalsServiceMockRecorder) Withdraw(ctx, userID, orderNumber, sum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockWithdrawalsService)(nil).Withdraw), ctx, userID, orderNumber, sum)
}
